"""drop altman_z and beneish_m columns

Revision ID: 1c80c1ee906b
Revises: f27cef38fc1a
Create Date: 2026-07-04 09:28:43.933639

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c80c1ee906b'
down_revision: Union[str, None] = 'f27cef38fc1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metrics_history', 'altman_z')
    op.drop_column('metrics_history', 'beneish_m')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics_history', sa.Column('beneish_m', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('metrics_history', sa.Column('altman_z', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
