"""add current_ratio to metrics_history

Revision ID: d41083ab7cff
Revises: 1c80c1ee906b
Create Date: 2026-07-04 12:51:38.009750

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd41083ab7cff'
down_revision: Union[str, None] = '1c80c1ee906b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('metrics_history', sa.Column('current_ratio', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('metrics_history', 'current_ratio')
    # ### end Alembic commands ###
